# Generated by Django 2.0.5 on 2018-07-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AG_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_cognome', models.CharField(max_length=50)),
                ('AG_matricola', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Indagato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IN_nome', models.CharField(max_length=50)),
                ('IN_cognome', models.CharField(max_length=50)),
                ('IN_data_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Magistrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MA_cognome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PR_prot', models.IntegerField()),
                ('PR_timestamp', models.DateTimeField(auto_now_add=True)),
                ('PR_tipologia', models.IntegerField(choices=[(1, 'Penale'), (2, 'Civile')])),
                ('PR_rgnr', models.CharField(max_length=10)),
                ('PR_fncr', models.IntegerField(choices=[(1, 'Ignoti'), (2, 'FNCR')])),
                ('PR_data_delega', models.DateField()),
                ('PR_attivita', models.TextField(blank=True, max_length=1000, null=True)),
                ('PR_data_restituzione', models.DateField()),
                ('PR_note', models.TextField(max_length=1000)),
                ('PR_agente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Agente')),
                ('PR_indagati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Indagato')),
                ('PR_magistrato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Magistrato')),
            ],
        ),
    ]
