# Generated by Django 2.0.5 on 2018-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='PR_data_restituzione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='PR_note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
